spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/admin/users/**,/auth/**,/users/**

        - id: salon-service
          uri: lb://salon-service
          predicates:
            - Path=/api/salon/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**

        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/category/**

        - id: service-offering
          uri: lb://service-offering
          predicates:
            - Path=/api/service-offering/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

        - id: notifications
          uri: lb://notifications
          predicates:
            - Path=/api/notifications/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs

server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8090/eureka/