export const CREATE_BOOKINGS_REQUEST = "CREATE_BOOKINGS_REQUEST";
export const CREATE_BOOKINGS_SUCCESS = "CREATE_BOOKINGS_SUCCESS";
export const CREATE_BOOKINGS_FAILURE = "CREATE_BOOKINGS_FAILURE";

export const FECTH_CUSTOMER_BOOKINGS_REQUEST = "FECTH_CUSTOMER_BOOKINGS_REQUEST";
export const FECTH_CUSTOMER_BOOKINGS_SUCCESS = "FECTH_CUSTOMER_BOOKINGS_SUCCESS";
export const FECTH_CUSTOMER_BOOKINGS_FAILURE = "FECTH_CUSTOMER_BOOKINGS_FAILURE";

export const FETCH_SALON_BOOKINGS_REQUEST = "FETCH_SALON_BOOKINGS_REQUEST";
export const FETCH_SALON_BOOKINGS_SUCCESS = "FETCH_SALON_BOOKINGS_SUCCESS";
export const FETCH_SALON_BOOKINGS_FAILURE = "FETCH_SALON_BOOKINGS_FAILURE";

export const FETCH_BOOKING_BY_ID_REQUEST = "FETCH_BOOKING_BY_ID_REQUEST";
export const FETCH_BOOKING_BY_ID_SUCCESS = "FETCH_BOOKING_BY_ID_SUCCESS";
export const FETCH_BOOKING_BY_ID_FAILURE = "FETCH_BOOKING_BY_ID_FAILURE";

export const UPDATE_BOOKING_STATUS_REQUEST = "UPDATE_BOOKING_STATUS_REQUEST";
export const UPDATE_BOOKING_STATUS_SUCCESS = "UPDATE_BOOKING_STATUS_SUCCESS";
export const UPDATE_BOOKING_STATUS_FAILURE = "UPDATE_BOOKING_STATUS_FAILURE";

export const GET_SALON_REPORT_REQUEST = "GET_SALON_REPORT_REQUEST";
export const GET_SALON_REPORT_SUCCESS = "GET_SALON_REPORT_SUCCESS";
export const GET_SALON_REPORT_FAILURE = "GET_SALON_REPORT_FAILURE";

export const FETCH_BOOKED_SLOTS_REQUEST = "FETCH_BOOKED_SLOTS_REQUEST";
export const FETCH_BOOKED_SLOTS_SUCCESS = "FETCH_BOOKED_SLOTS_SUCCESS";
export const FETCH_BOOKED_SLOTS_FAILURE = "FETCH_BOOKED_SLOTS_FAILURE";